### ISSUE TITLE
Gambling Planning 

### ISSUE THREAD

**Issue by alishahussain** [dino596/gambling#1]
# Tasks

- [ ] login page with Javascript
- [ ] kahoot quiz backend for teacher input
- [ ] leaderboard
- [ ] homepage of games to choose from
- [ ] Blackjack Game
- [ ] Dice Game
- [ ] Score Analysis
- [ ] Plinko Balls

**Comment by alishahussain** [comment]
## Arthur : Scrum Master
- [ ]  
## Hanlun : 
- [ ]  
## Saraas : 
- [ ] 
## Alisha : 
- [ ]
